NAME		= zsh
REVISION	= 2
VERSION		= 5.0.5
DISTFILE	= zsh-${VERSION}.tar.bz2
DISTURL		= http://sourceforge.net/projects/zsh/files/zsh/${VERSION}/zsh-${VERSION}.tar.bz2/download

.include "../../mk/base.mk"
