NAME		= gmake
VERSION		= 4.0
DISTFILE	= make-${VERSION}.${ARCHIVE}
SRCDIR		= make-${VERSION}
DISTURL		= ftp://ftp.gnu.org/pub/gnu/make/${DISTFILE}

EXTRA_CONFIGURE_ARGS	= --program-prefix=g

.include "../../mk/base.mk"
