VIM_VERSION	= 7.4
SRCDIR		= vim74

NAME		= vim
VERSION		= ${VIM_VERSION}
DISTFILE	= vim-${VERSION}.tar.bz2
DISTURL		= ftp://ftp.vim.org/pub/vim/unix/vim-${VIM_VERSION}.tar.bz2

.include "../../mk/base.mk"
