NAME		= epic5
DESC		= Enhanced Programming IRC Client (version 5)
VERSION		= 1.1.7
DISTURL		= ftp://ftp.epicsol.org/pub/epic/EPIC5-PRODUCTION/epic5-${VERSION}.${ARCHIVE}

EXTRA_CONFIGURE_ARGS	= --without-perl

.include "../../mk/base.mk"
